[package]
name = "cherl-script-util"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.141"
serde_toml = "0.0.1"
anyhow ={ workspace = true }