[package]
name = "cherl-remote-util"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = "0.12.22"
anyhow = { workspace = true }
indicatif = {workspace = true}
cherl-util = {path = "../cherl-util"}